services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - web
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - web

  php:
    build: .
    volumes:
      - ./:/var/www/html
      - /var/log/apache2/app:/var/log/apache2/
    networks:
      - web
  
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 8080:8080
    networks:
      - web

networks:
  web: